version: "3"

services:

  jenkins:
    image: jenkinsci/blueocean
    user: "root"
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./var/run/docker.sock:/var/run/docker.sock
      - ./:/home
    ports:
      - "8085:8080"




